### PR TITLE
Finishing up

### PR DESCRIPTION
**Pull request by jmbohan**

### CODE REVIEW

**Comment by DeborahK** [comment]
Hey Jason! Hope you are enjoying the course! 

I assume you don't mean to commit changes to my repo? If no, please close this. Thanks!

**Comment by jmbohan** [comment]
Sorry. I had some git CLI problems or human err..

**Comment by DeborahK** [comment]
No problem. We all struggle with GitHub from time to time. :-)

All the best.

**Comment by jmbohan** [comment]
your classes a delightful by the way. Thank you for the help!

**Pull request closed without merging**
